# Generated by Django 5.2.11 on 2026-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField(default=[])),
            ],
        ),
    ]
